// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0zhAbi9A1pnY2Yg8X44AH5hGBxNbaWsE',
    appId: '1:894329943560:android:7954fbdb6c222cd8e983bd',
    messagingSenderId: '894329943560',
    projectId: 'biu-lose-and-found',
    storageBucket: 'biu-lose-and-found.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnS0NENQXuZySPSapamOLVLNEj98pHoOI',
    appId: '1:894329943560:ios:9dbd1dce9876f5d7e983bd',
    messagingSenderId: '894329943560',
    projectId: 'biu-lose-and-found',
    storageBucket: 'biu-lose-and-found.firebasestorage.app',
    iosClientId: '894329943560-8uhdi108hjcrgam200v0t006di3683d3.apps.googleusercontent.com',
    iosBundleId: 'com.exampe.belteiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnS0NENQXuZySPSapamOLVLNEj98pHoOI',
    appId: '1:894329943560:ios:697174fefe2b2605e983bd',
    messagingSenderId: '894329943560',
    projectId: 'biu-lose-and-found',
    storageBucket: 'biu-lose-and-found.firebasestorage.app',
    iosClientId: '894329943560-k40u5u63e4pcev8jga96168vpa4jk2kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.belteiApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBveId-ui8elVf_ac1-yzdwiBnEL_CTqaA',
    appId: '1:894329943560:web:093573773770f481e983bd',
    messagingSenderId: '894329943560',
    projectId: 'biu-lose-and-found',
    authDomain: 'biu-lose-and-found.firebaseapp.com',
    storageBucket: 'biu-lose-and-found.firebasestorage.app',
    measurementId: 'G-K4NJ9KCE5D',
  );
}
